packages:
  - apps/*
  - packages/*

overrides:
  multer: 2.3.0

allowBuilds:
  '@parcel/watcher': true
  argon2: true
  esbuild: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - argon2
  - esbuild
