<template>
  <div><div class="d-flex flex-wrap align-end justify-space-between ga-4 mb-6"><div><div class="eyebrow mb-2">Stammdaten</div><h1 class="page-heading">Kunden</h1><p class="muted mt-2">Kontakte pflegen, ohne historische Rechnungen zu verändern.</p></div><v-btn color="primary" size="large" prepend-icon="mdi-account-plus-outline" @click="openCreate">Neuer Kunde</v-btn></div>
    <v-card class="surface-card pa-4 mb-5"><div class="d-flex flex-wrap ga-3"><v-text-field v-model="search" label="Kunden suchen" prepend-inner-icon="mdi-magnify" clearable hide-details class="flex-grow-1" @keyup.enter="load" /><v-switch v-model="includeArchived" label="Archivierte anzeigen" color="primary" hide-details @update:model-value="load" /><v-btn color="primary" variant="tonal" height="48" @click="load">Suchen</v-btn></div></v-card>
    <v-row v-if="loading"><v-col v-for="n in 6" :key="n" cols="12" md="6" xl="4"><v-skeleton-loader type="article" class="surface-card rounded-xl" /></v-col></v-row>
    <v-row v-else-if="customers.length"><v-col v-for="customer in customers" :key="customer.id" cols="12" md="6" xl="4"><v-card class="surface-card pa-5 h-100"><div class="d-flex align-start"><v-avatar color="primary" variant="tonal" size="46">{{ initials(customer) }}</v-avatar><div class="ml-3 min-width-0"><div class="font-weight-bold text-truncate">{{ customer.company || customer.name }}</div><div v-if="customer.company" class="text-body-2 muted">{{ customer.name }}</div><v-chip v-if="customer.archivedAt" size="x-small" color="grey" class="mt-1">Archiviert</v-chip></div><v-spacer/><v-menu><template #activator="{props}"><v-btn v-bind="props" icon="mdi-dots-horizontal" variant="text" /></template><v-list><v-list-item prepend-icon="mdi-pencil-outline" title="Bearbeiten" @click="openEdit(customer)"/><v-list-item :prepend-icon="customer.archivedAt?'mdi-archive-arrow-up-outline':'mdi-archive-outline'" :title="customer.archivedAt?'Reaktivieren':'Archivieren'" @click="toggleArchive(customer)"/></v-list></v-menu></div><v-divider class="my-4"/><div class="text-body-2"><div><v-icon icon="mdi-map-marker-outline" size="17" class="mr-2"/>{{ customer.street }}, {{ customer.postalCode }} {{ customer.city }}</div><div v-if="customer.email" class="mt-2"><v-icon icon="mdi-email-outline" size="17" class="mr-2"/>{{ customer.email }}</div><div v-if="customer.customerNumber" class="mt-2 muted">Kundennummer {{ customer.customerNumber }}</div></div></v-card></v-col></v-row>
    <v-card v-else class="surface-card text-center pa-14"><div class="empty-art"><v-icon icon="mdi-account-group-outline" size="34"/></div><h2 class="text-h6">Noch keine Kunden</h2><p class="muted mt-2 mb-5">Lege einen Kunden an, um die erste Rechnung zu erstellen.</p><v-btn color="primary" @click="openCreate">Kunde anlegen</v-btn></v-card>
    <v-pagination v-if="totalPages>1" v-model="page" :length="totalPages" class="mt-5" @update:model-value="load" />
    <v-dialog v-model="dialog" max-width="680" persistent><v-card class="pa-5 pa-sm-7"><div class="d-flex justify-space-between align-center mb-5"><div><div class="eyebrow">{{ editingId?'Bearbeiten':'Neu anlegen' }}</div><h2 class="text-h5 font-weight-bold mt-1">Kundendaten</h2></div><v-btn icon="mdi-close" variant="text" @click="dialog=false"/></div><v-form ref="formRef" @submit.prevent="save"><v-row dense><v-col cols="12" sm="8"><v-text-field v-model="form.company" label="Firma (optional)"/></v-col><v-col cols="12" sm="4"><v-text-field v-model="form.customerNumber" label="Kundennummer"/></v-col><v-col cols="12"><v-text-field v-model="form.name" :label="form.company?'Kontaktperson':'Name'" :rules="[required]"/></v-col><v-col cols="12"><v-text-field v-model="form.street" label="Straße und Hausnummer" :rules="[required]"/></v-col><v-col cols="5"><v-text-field v-model="form.postalCode" label="PLZ" :rules="[required]"/></v-col><v-col cols="7"><v-text-field v-model="form.city" label="Ort" :rules="[required]"/></v-col><v-col cols="12" sm="4"><v-select v-model="form.country" label="Land" :items="countries"/></v-col><v-col cols="12" sm="8"><v-text-field v-model="form.email" label="E-Mail" type="email"/></v-col><v-col cols="12"><v-text-field v-model="form.phone" label="Telefon (optional)"/></v-col></v-row><div class="d-flex justify-end ga-3 mt-3"><v-btn variant="text" @click="dialog=false">Abbrechen</v-btn><v-btn color="primary" type="submit" :loading="saving">Speichern</v-btn></div></v-form></v-card></v-dialog>
  </div>
</template>
<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{api,apiMessage}from'../api/client';import{useUiStore}from'../stores/ui';
interface Customer{id:string;customerNumber:string|null;name:string;company:string|null;street:string;postalCode:string;city:string;country:string;email:string|null;phone:string|null;archivedAt:string|null}
const customers=ref<Customer[]>([]),loading=ref(true),saving=ref(false),dialog=ref(false),editingId=ref(''),search=ref(''),includeArchived=ref(false),page=ref(1),totalPages=ref(1);const ui=useUiStore();const formRef=ref<{validate():Promise<{valid:boolean}>}>();const blank=()=>({customerNumber:'',name:'',company:'',street:'',postalCode:'',city:'',country:'DE',email:'',phone:''});const form=reactive(blank());const countries=[{title:'Deutschland',value:'DE'},{title:'Österreich',value:'AT'},{title:'Schweiz',value:'CH'},{title:'Frankreich',value:'FR'},{title:'Niederlande',value:'NL'}];const required=(v:unknown)=>Boolean(String(v??'').trim())||'Pflichtfeld';
async function load(){loading.value=true;try{const r=await api.get('/customers',{params:{search:search.value,includeArchived:includeArchived.value,page:page.value,pageSize:24}});customers.value=r.data.data;totalPages.value=r.data.meta.totalPages;}catch(e){ui.notify(apiMessage(e),'error')}finally{loading.value=false}}
function openCreate(){editingId.value='';Object.assign(form,blank());dialog.value=true}function openEdit(c:Customer){editingId.value=c.id;Object.assign(form,{customerNumber:c.customerNumber??'',name:c.name,company:c.company??'',street:c.street,postalCode:c.postalCode,city:c.city,country:c.country,email:c.email??'',phone:c.phone??''});dialog.value=true}
async function save(){const v=await formRef.value?.validate();if(!v?.valid)return;saving.value=true;try{editingId.value?await api.patch(`/customers/${editingId.value}`,form):await api.post('/customers',form);ui.notify(editingId.value?'Kunde aktualisiert.':'Kunde angelegt.');dialog.value=false;await load()}catch(e){ui.notify(apiMessage(e),'error')}finally{saving.value=false}}
async function toggleArchive(c:Customer){try{await api.post(`/customers/${c.id}/${c.archivedAt?'unarchive':'archive'}`);ui.notify(c.archivedAt?'Kunde reaktiviert.':'Kunde archiviert.');await load()}catch(e){ui.notify(apiMessage(e),'error')}}function initials(c:Customer){return(c.company||c.name).split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}onMounted(load);
</script>
<style scoped>.min-width-0{min-width:0}</style>
